version: '3'

networks:
  postech_net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - postech_net

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ms_pagamento}
      MYSQL_USER: ${MYSQL_USER:-postech}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-postech}
    ports:
      - '3307:3306'
    networks:
      - postech_net
  
  swagger-ui:
    depends_on:
      - app
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/openapi.yaml

